[features]
seeds = false
skip-lint = false

[programs.localnet]
equilibrate = "Equi1uCecmsviNx18BnTiDDFrGoDFzoUsKHVu9btACaM"

[programs.devnet]
equilibrate = "Equi1uCecmsviNx18BnTiDDFrGoDFzoUsKHVu9btACaM"

[programs.mainnet]
equilibrate = "Equi1uCecmsviNx18BnTiDDFrGoDFzoUsKHVu9btACaM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./kp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
