[features]
seeds = false
skip-lint = false

[programs.localnet]
equilibrate = "Equi1CUTu17WagNVmpFq4SvcqvrEeNYWqqgzw4MppmjS"

[programs.devnet]
equilibrate = "Equi1CUTu17WagNVmpFq4SvcqvrEeNYWqqgzw4MppmjS"

[programs.mainnet]
equilibrate = "Equi1CUTu17WagNVmpFq4SvcqvrEeNYWqqgzw4MppmjS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/austin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
